apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: conda-dev-image
spec:
  type: image
  params:
  - name: url
    value: sys-powerai-condaimages-docker-local.artifactory.swg-devops.com/pai-conda3:next-dev-rhel-ppc64le
