apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: foo-trig
      template:
        name: thetemplatetrigger
      bindings:
        - ref: thetriggerbinding
