apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: docker-target
spec:
  type: image
  params:
    - name: url
      value:  na.artifactory.swg-devops.com/artifactory/sys-powerai-condaimages-docker-local.artifactory.swg-devops.com/
