apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata: 
  name: repo2
spec: 
  resources: 
    - 
      name: source
      type: git
  taskRef: 
    name: invoke
  tasks: 
    - 
      name: invoke
      resources: 
        inputs: 
          - 
            name: source
            resource: source