apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata: 
  name: repo2
resources: 
  - 
    name: source
    type: git
spec: ~
tasks: 
  - name: invoke
    resources: 
      inputs: 
        - name: source
          resource: source
    taskRef: 
      name: invoke