apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata: 
  name: repo2
spec: 
  resources: 
    - name: source
      type: git
  tasks: 
    - name: invoke1
      taskRef: 
        - name: cloneandrun-a
      resources: 
        inputs: 
          - name: source
            resource: source
    - name: cloneandrun-b
      runAfter: [cloneandrun-a]
      taskRef: 
        - name: cloneandrun-b
      resources: 
        inputs: 
          - name: source
            resource: source

