apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata: 
  name: repo2
spec: 
  resources: 
    - name: source
      type: git
  tasks: 
    - name: invoke1
      taskRef: 
        - name: TaskA
      resources: 
        inputs: 
          - name: source
            resource: source
    - name: TaskB
      runAfter: [TaskA]
      taskRef: 
        - name: TaskB
      resources: 
        inputs: 
          - name: source
            resource: source

