apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata: 
  name: repo2
spec: 
  resources: 
    - 
      name: source
      type: git
  tasks: 
  - name: invoke1
    taskRef: 
    - name: invoke
    resources: 
      inputs: 
      - name: source
        resource: source
  - name: invoke2
    runAfter: invoke1
    taskRef: 
    - name: invoke2
    resources: 
      inputs: 
      - name: source
        resource: source