apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata: 
  name: repo2
spec: 
  resources: 
    - name: source
      type: git
  tasks: 
    - name: invoke1
      resources: 
        inputs: 
          - name: source
            resource: source
      taskRef: 
        - name: invoke1
    - name: invoke2
      resources: 
        inputs: 
          - name: source
            resource: source
      runAfter: invoke1
      taskRef: 
        - name: invoke2
