apiVersion: v1
kind: Secret
metadata:
  name: github-token
  annotations:
    tekton.dev/git-0: github.ibm.com
type: kubernetes.io/ssh-auth
data:
  token: "N2Y3MDRlNjY5Y2ZlNzFjYzZhZThkNTEyM2VjNjk2NDE4ZjFlYmIxMAo="
