
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clone-opence
spec:
  inputs:
    resources:
    - name: git-pipe-resource
      type: git
  params:
  - name: PACKAGE_NAME
    type: string
    default: "torchtext-feedstock"
  - name: BUILD_SCRIPT_NAME
    type: string
    default: "build.sh"
  - name: GIT_URL
    type: string
    default: "https://github.ibm.com/ketank/tensorflow-feedstock.git"
  steps:
    - name: view-repo
      image: ubuntu
      command: ['ls', '/workspace/source/']
