apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: pkg-build
spec:
  inputs:
    resources:
    - name: git-pipe-resource
      type: git
  outputs:
    resources:
    - name: docker-pull-resource
      type: image
  params:
  - name: SERVER
    type: string
    default: "https://na.artifactory.swg-devops.com/artifactory"    
  - name: IMAGE_NAME
    type: string
    default: "pai-conda3"
  - name: CHANNEL
    type: string
    default: "sys-powerai-condaimages-docker-local.artifactory.swg-devops.com"
  - name: TAG_NAME
    type: string
    default: "next-dev-rhel-x86_64"
  steps:
    - name: pull-image
      image: $(params.CHANNEL)/$(params.IMAGE_NAME):$(params.TAG_NAME)
      scripts: |
        cat /etc/os-release
        ls /workspace/git-pipe-resource
