apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-universe-resource
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.ibm.com/open-ce/universe.git
