apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: clone-build-run
  namespace: tekton-pipelines
spec:
  inputs:
    resources:
      - name: git-pipe-resource
        resourceRef:
          name: git-pipe-resource
  params:
    - name: GIT_URL
      value: https://github.ibm.com/open-ce/$(params.PKG_NAME)-feedstock.git
  serviceAccountName: build-bot
  taskRef:
    name: clone-build
