apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: clone-build-run
  namespace: tekton-pipelines
spec:
  inputs:
    resources:
      - name: git-pipe-resource
        resourceRef:
          name: git-pipe-resource
      - name: git-universe-resource
        resourceRef:
          name: git-universe-resource
  params:
    - name: PKG_NAME
      value: numactl-feedstock
    - name: PKG_URL
      value: https://github.ibm.com/open-ce/$(params.PKG_NAME).git
  serviceAccountName: build-bot
  taskRef:
    name: clone-build
