apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: clone-build
spec:
  inputs:
    resources:
    - name: git-pipe-resource
      type: git
    - name: git-universe-resource
      type: git
  params:
  - name: OUTPUT_FOLDER
    type: string
    default: /home/builder/
  - name: CHANNEL_NAME
    type: string
    default: sys-powerai-next-conda-local
  - name: PKG_NAME
    type: string
    default: numactl-feedstock
  - name: PKG_URL
    type: string
    default: https://github.ibm.com/open-ce/$(params.PKG_NAME).git
  steps:
    - name: view-repo
      image: sys-powerai-condaimages-docker-local.artifactory.swg-devops.com/pai-conda3:next-dev-rhel-x86_64
      env:
        - name: ARTIFACTORY_CREDS_USR
          value: ketank@us.ibm.com
        - name: ARTIFACTORY_CREDS_PSW
          valueFrom:
            secretKeyRef:
              name: art-token
              key: .dockerconfigjson
        - name: CHANNEL_FULLNAME
          value: https://$(env.ARTIFACTORY_CREDS_USR):$(env.ARTIFACTORY_CREDS_PSW)@na.artifactory.swg-devops.com/artifactory/api/conda/sys-powerai-next-conda-local
      script: |
        sudo ln -s /tekton/creds/.gitconfig /home/builder/.gitconfig
        sudo cp /tekton/creds/.git-credentials /home/builder/.git-credentials
        sudo mv /workspace/git-pipe-resource /workspace/$(params.PKG_NAME)
        sudo mv /workspace/git-universe-resource /workspace/numactl-feedstock/universe
        cd /workspace/numactl-feedstock/
        sh universe/ci_common_scripts/run_build.sh
        ls -la /home/builder/
        
