apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: clone-build
spec:
  inputs:
    resources:
    - name: git-pipe-resource
      type: git
    - name: git-universe-resource
      type: git
  params:
  - name: PKG_NAME
    type: string
    default: numactl-feedstock
  - name: PKG_URL
    type: string
    default: https://github.ibm.com/open-ce/$(params.PKG_NAME).git
  steps:
    - name: view-repo
      image: sys-powerai-condaimages-docker-local.artifactory.swg-devops.com/pai-conda3:next-dev-rhel-x86_64
      script: |
        sudo cp /tekton/creds/.gitconfig /home/builder/
        sudo cp /tekton/creds/.git-credentials /home/builder/
        sudo cat /home/builder/.git-credentials
        sudo mv /workspace/git-pipe-resource /workspace/$(params.PKG_NAME)
        sudo mv /workspace/git-universe-resource /workspace/numactl-feedstock/universe
        cd /workspace/numactl-feedstock/
        python /universe/builder/build_package.py --conda_build_config /universe/conda_build_config.yaml --output_folder=/home/builder/ --channels https://na.artifactory.swg-devops.com/artifactory/api/conda/sys-powerai-next-conda-local
        
