apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener-interceptor
spec:
  serviceType: LoadBalancer
  triggers:
  - name: pr-trig
    interceptor:
    bindings:
      - name: review-pipeline-binding
    template:
      name: review-pipeline-template
