name: CI
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ lint-check ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Minikube
      id: minikube
      uses: CodingNagger/minikube-setup-action@v1.0.2
    - name: Launch Minikube
      run: eval ${{ steps.minikube.outputs.launcher }}
    - name: Check pods
      run: |
        kubectl get pods
        curl -sLO https://github.com/argoproj/argo/releases/download/v0.0.0-dev-dataflow-24/argo-linux-amd64.gz -o argo-linux.gz

        # Unzip and make binary executable
        gunzip argo-linux.gz
        chmod +x argo-linux

        # Move binary to path
        mkdir -p $HOME/bin
        mv ./argo-linux $HOME/bin/argo
        PATH=$HOME/bin:$PATH

        echo "Testing out argo"
        pwd && ls && argo --help | grep lint
        argo template lint templates

    
    
