# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ lint-check ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          curl -sL https://github.com/argoproj/argo-workflows/releases/download/v2.11.0/argo-linux-amd64.gz -o argo-linux.gz

          # Unzip and make binary executable
          gunzip argo-linux.gz
          chmod +x argo-linux

          # Move binary to path
          mkdir -p $HOME/bin
          mv ./argo-linux $HOME/bin/argo
          PATH=$HOME/bin:$PATH

          echo "Testing out argo"
          argo list
          #echo "Testing out argo"
          #argo list

